### ISSUE TITLE
Set limit bounds based on dataframe/groupby/aggregation

### ISSUE THREAD

**Issue by dalogsdon** [ibm-et/urth-viz-vega#1]
Currently the limit can be set to whatever arbitrary bounds are defined in the UI. See if there is a way to get the actual limit from the data.

**Comment by lbustelo** [comment]
My 2 cents... Computing counts can be an expensive operation. Should be an opt in option.

**Comment by peller** [comment]
@lbustelo @dalogsdon so maybe this is a wontfix?

**Comment by dalogsdon** [comment]
Won't fix unless it becomes a future issue.
