### ISSUE TITLE
one-line display method

### ISSUE THREAD

**Issue by peller** [ibm-et/urth-viz-vega#3]
Need some sugar for declarative html from Python, R, etc. to examine a dataframe.  Could be a method like `display(...)` or if the hooks are there to override the default display of a dataframe, create an explorer widget instead?

**Comment by poplav** [comment]
I was investigating in R a simple example was:
On the kernel init/setup export a support function to the user env like:

```
makeDisplay <- function(df) {
    IRdisplay::display_html(paste("
        <template is='urth-core-bind'>
            <urth-core-dataframe id='f3' ref='", df, "' value='{{df}}' auto></urth-core-dataframe>
            <template is='dom-repeat' items='{{df.data}}'>
              <div class='info'>
                    <span class='test3'>{{item.0}}</span>, <span>{{item.1}}</span>
              </div>
            </template>
        </template>
    "))
}
```

So, in the notebook all the user has to do in the cell is `makeDisplay("aDataFrame")` to view the df.

**Comment by peller** [comment]
@poplav if you're inspired to make a branch/PR for support in various languages that would be _awesome_

**Comment by poplav** [comment]
I'll begin a branch for this.  I'll start with the example above to stub out the process, but this could lead to html generation based off the parameter type of the display function?  
The goal would be to wrap the examples in `urth-viz-query.ipynb` as a one line funciton call in the kernel language, I am assuming.

**Comment by peller** [comment]
Ideally, I think the definition would come with a widget, perhaps the explorer?

**Comment by poplav** [comment]
Resolved by https://github.com/jupyter-incubator/declarativewidgets/pull/439
