### ISSUE TITLE
collapsible sections

### ISSUE THREAD

**Issue by peller** [ibm-et/urth-viz-vega#5]
cards should be collapsible. perhaps entire config section should be collapsible or toggled?

**Comment by dalogsdon** [comment]
Yes, I think both. Later iterations of this could focus on dashboard integration, where controls are visible in notebook and hidden in dashboard.

**Comment by dalogsdon** [comment]
Note to self: also need to change from fixed widths to flex layout so resizing the viz works properly.

**Comment by peller** [comment]
recommend fixed width on left, remainder to right, rather than proportional columns

**Comment by dalogsdon** [comment]
I made individual explorer cards collapsible, next I will make the entire config section collapsible.

**Comment by peller** [comment]
@dalogsdon anything left here or can we close?

**Comment by dalogsdon** [comment]
This covers basic functionality, we can close.
