### ISSUE TITLE
dashboard integration

### ISSUE THREAD

**Issue by peller** [ibm-et/urth-viz-vega#8]
placeholder for investigation for how to integrate the explorer with the dashboard.  Besides #5 (configurable controls)  Menu integration? other?

**Comment by dalogsdon** [comment]
Some Initial ideas:
1. Auto show/hide explorer controls based on view state (notebook=show, dashboard=hide)
2. Button in dashboard view to add a chart using explorer. Some wizard might have to show up to configure before it is added in the dashboard layout. But how to hook up data?

**Comment by dalogsdon** [comment]
Moved to https://github.com/jupyter-incubator/declarativewidgets_explorer/issues/9
