### ISSUE TITLE
more chart types

### ISSUE THREAD

**Issue by peller** [ibm-et/urth-viz-vega#9]
Add more vega-lite chart types?  vega-based charts? (including mapping)

**Comment by dalogsdon** [comment]
I think a few pretty ones to enhance the demo would be good. Definitely mapping, and perhaps one or two unusual ones. Something with circles (but not a circle packing chart) is always pretty.

**Comment by peller** [comment]
moved to https://github.com/jupyter-incubator/declarativewidgets_explorer/issues/6
